PlaceOS/frontend-loader

- shard.lock
- shard.yml
- spec/helper.cr
- spec/loader_spec.cr
- spec/repositories_spec.cr
- src/placeos-frontends/loader.cr
Fetch branches and checkout the current branch if the repository is already present.
> fix: correct flow for pulling a new branch

- Dockerfile
- Add `openssh`
- Add `ca-certificates`
> build(Dockerfile): add ssh and ca-certs

- Dockerfile.test
- docker-compose.yml
- entrypoint.sh
- shard.lock
- shard.yml
- spec/helper.cr
- src/placeos-frontends/client.cr
- test
Also adds a docker compose environment for specs
> build: bump shards

- src/placeos-frontends/loader.cr
Pull username/password from the repository model when performing clone operations.
Fixes #14
> feat: support git user/pass

- Dockerfile
- Dockerfile.test
- shard.lock
- shard.override.yml
- spec/loader_spec.cr
- src/placeos-frontends/loader.cr
> chore: bump crystal

- shard.lock
- shard.yml
- src/placeos-frontends/loader.cr
Adds the option to force pull an interface repository
> fix(loader): force pull repositories

- .travis.yml
- Dockerfile
- Dockerfile.test
- shard.lock
- shard.yml
> chore: bump to crystal 1.0.0

- .github/workflows/ci.yml
- Dockerfile
- docker-compose.yml
- entrypoint.sh
- shard.lock
- shard.yml
- spec/helper.cr
- spec/loader_spec.cr
- src/placeos-frontends/controllers/repositories.cr
- src/placeos-frontends/loader.cr
Ensure the `updated_at` time changes when the repository's commit has been changed.
> fix(loader): update the timestamp when updating the commit

- src/placeos-frontends/loader.cr
Reduces timestamp update frequency
> fix(loader): update commit if more than a minute elapsed

- shard.lock
- shard.yml
- src/config.cr
- src/constants.cr
- src/logging.cr
- Configure `Log.progname`
- Factor `Log` configuration into `PlaceOS::Frontends::Logging`
> feat(logging): configure progname

- .github/workflows/ci.yml
- Dockerfile
- Dockerfile.test
- shard.lock
- shard.yml
- src/placeos-frontends/loader.cr
Fixes credentials not getting decrypted from the repository model
> fix(loader): decrypt creds

- Dockerfile
- README.md
- shard.yml
- spec/helper.cr
- spec/loader_spec.cr
- spec/repositories_spec.cr
- spec/root_spec.cr
- src/app.cr
- src/config.cr
- src/constants.cr
- src/logging.cr
- src/placeos-frontend-loader.cr
- src/placeos-frontend-loader/api/base.cr
- src/placeos-frontend-loader/api/repositories.cr
- src/placeos-frontend-loader/api/root.cr
- src/placeos-frontend-loader/client.cr
- src/placeos-frontend-loader/error.cr
- src/placeos-frontend-loader/loader.cr
- src/placeos-frontends.cr
Closes place-labs/product-team-bau/issues/11
> refactor: frontends -> frontend-loader

- CHANGELOG.md
- shard.lock
Closes #34 
See https://github.com/PlaceOS/compiler/issues/39 for further information
> fix: allow updates to username and password

- shard.lock
- shard.yml
- spec/helper.cr
- spec/loader_spec.cr
- spec/repositories_spec.cr
- src/placeos-frontend-loader/loader.cr
Removes spurious updates that were causing a cycle
> fix(loader): avoid update cycle

- shard.lock
- shard.yml
- src/placeos-frontend-loader/api/repositories.cr
- src/placeos-frontend-loader/client.cr
Account for branches when fetching interface commits
> fix: factor branch when fetching commits

- Dockerfile
Update default healthcheck URI to new API path
> Fix healthcheck URI

- shard.lock
Bump the db driver to include reconnection fixes
> build(shard.lock): bump rethinkdb

- shard.lock
- shard.yml
**Description of the change**
Adds `JSON::Serializable` serialisation!
> fix: bump `placeos-models`

- Dockerfile
- shard.lock
- shard.yml
- src/app.cr
bumps version and ensures there is an error message
> chore(Dockerfile): bump crystal version

- shard.lock
- shard.yml
- src/app.cr
- src/logging.cr
> fix(logging): bring inline with other services

- spec/api/repositories_spec.cr
- src/placeos-frontend-loader/api/remote/generic.cr
- src/placeos-frontend-loader/api/remote/github.cr
- src/placeos-frontend-loader/api/remote/gitlab.cr
- src/placeos-frontend-loader/api/remote/remote.cr
- src/placeos-frontend-loader/api/repositories.cr
- src/placeos-frontend-loader/loader.cr
probably could do with a cleanup but working and tests passing
> feat: add support for generic repositories

- spec/api/remotes_spec.cr
- src/placeos-frontend-loader/api/remote/generic.cr
- src/placeos-frontend-loader/api/remote/git.cr
- src/placeos-frontend-loader/api/remote/github.cr
- src/placeos-frontend-loader/api/remote/remote.cr
- src/placeos-frontend-loader/client.cr
> fix(remote): only listing a single commit

- shard.lock
- spec/loader_spec.cr
- src/placeos-frontend-loader/loader.cr
provide a feedback mechanism for the pull button on frontends
> fix(loader): provide feedback of the deployed commit hash

- .gitignore
- Dockerfile
- OPENAPI_DOC.yml
- docker-compose.yml
- shard.lock
- shard.yml
- spec/api/remotes_spec.cr
- spec/helper.cr
- spec/root_spec.cr
- src/app.cr
- src/constants.cr
- src/placeos-frontend-loader/api/base.cr
- src/placeos-frontend-loader/api/remotes.cr
- src/placeos-frontend-loader/api/repositories.cr
- src/placeos-frontend-loader/api/root.cr
also updates API to self documenting version of action controller
> feat: add support for ARM64 images

- spec/loader_spec.cr
- src/placeos-frontend-loader/loader.cr
> feat(loader): remove git folder once downloaded

- spec/loader_spec.cr
- src/placeos-frontend-loader/loader.cr
caused by crystal lang bug https://github.com/crystal-lang/crystal/issues/13629
> fix(loader): ensure sub directories are updated for www-core

- docker-compose.yml
- shard.lock
- spec/loader_spec.cr
- src/config.cr
- test
related to https://github.com/crystal-lang/crystal/pull/15510
> fix: file copy issue with some volumes
